automation:
  - alias: Smart Switch 1 Single Press
    description: ''
    trigger:
    - event_data:
        event: 1002
        id: smart_switch_1
      event_type: deconz_event
      platform: event
    condition: []
    action:
    - entity_id: light.living_room_ceiling
      service: light.toggle
  - alias: Smart Switch 1 Double Press
    description: ''
    trigger:
    - event_data:
        event: 1004
        id: smart_switch_1
      event_type: deconz_event
      platform: event
    condition:
    - condition: state
      entity_id: light.living_room_ceiling
      state: 'on'
    action:
    - data_template:
        entity_id: input_number.living_room_ceiling_brightness_step
        value: >-
          {% set state = states.input_number.living_room_ceiling_brightness.state | int %}
          {% if state >= 100 %}
            {% set state = -10 %}
          {% elif state <= 10 %}
            {% set state = 10 %}
          {% else %}
            {% set state = states.input_number.living_room_ceiling_brightness_step.state | int %}
          {% endif %}
          {{ state | int }}
      entity_id: input_number.living_room_ceiling_brightness_step
      service: input_number.set_value
    - data_template:
        entity_id: input_number.living_room_ceiling_brightness
        value: >-
          {% set state = states.input_number.living_room_ceiling_brightness.state | int %}
          {% if state >= 100 %}
            {% set state = 90 %}
          {% elif state <= 10 %}
            {% set state = 20 %}
          {% else %}
            {% set step = states.input_number.living_room_ceiling_brightness_step.state | int %}
            {% set state = state + step %}
          {% endif %}
          {{ state | int }}
      entity_id: input_number.living_room_ceiling_brightness
      service: input_number.set_value
    - data_template:
        entity_id: light.living_room_ceiling
        brightness_pct: '{{ states.input_number.living_room_ceiling_brightness.state | int }}'
      entity_id: light.living_room_ceiling
      service: light.turn_on
  - alias: Smart Switch 1 Long Press
    description: ''
    trigger:
    - event_data:
        event: 1003
        id: smart_switch_1
      event_type: deconz_event
      platform: event
    condition:
    - condition: state
      entity_id: light.living_room_ceiling
      state: 'on'
    action:
    - data_template:
        entity_id: input_number.living_room_ceiling_mired_step
        value: >-
          {% set state = states.input_number.living_room_ceiling_mired.state | float %}
          {% if state >= 500 %}
            {% set state = -34.7 %}
          {% elif state <= 153 %}
            {% set state = 34.7 %}
          {% else %}
            {% set state = states.input_number.living_room_ceiling_mired_step.state | float %}
          {% endif %}
          {{ state | float }}
      entity_id: input_number.living_room_ceiling_mired_step
      service: input_number.set_value
    - data_template:
        entity_id: input_number.living_room_ceiling_mired
        value: >-
          {% set state = states.input_number.living_room_ceiling_mired.state | float %}
          {% set step = states.input_number.living_room_ceiling_mired_step.state | float %}
          {% if (state + step) >= 500 %}
            {% set state = 500 %}
          {% elif (state + step) <= 153 %}
            {% set state = 153 %}
          {% else %}
            {% set state = state + step %}
          {% endif %}
          {{ state | int }}
      entity_id: input_number.living_room_ceiling_mired
      service: input_number.set_value
    - data_template:
        entity_id: light.living_room_ceiling
        color_temp: '{{ states.input_number.living_room_ceiling_mired.state | int }}'
      entity_id: light.living_room_ceiling
      service: light.turn_on
  - alias: Smart Switch 1 Shake
    description: ''
    trigger:
    - event_data:
        event: 1007
        id: smart_switch_1
      event_type: deconz_event
      platform: event
    condition:
    - condition: state
      entity_id: light.living_room_ceiling
      state: 'on'
    action:
    - data_template:
        entity_id: input_number.living_room_ceiling_mired
        value: >-
          {% set state = states.input_number.living_room_ceiling_mired.state | float %}
          {% if state != 500 %}
            {% set state = 500 %}
          {% else %}
            {% set state = 153 %}
          {% endif %}
          {{ state | int }}
      entity_id: input_number.living_room_ceiling_mired
      service: input_number.set_value
    - data_template:
        entity_id: light.living_room_ceiling
        color_temp: '{{ states.input_number.living_room_ceiling_mired.state | int }}'
      entity_id: light.living_room_ceiling
      service: light.turn_on
  - alias: Smart Switch 2 Single Press
    description: ''
    trigger:
    - event_data:
        event: 1002
        id: smart_switch_2
      event_type: deconz_event
      platform: event
    condition: []
    action:
    - entity_id: light.balcony_ceiling
      service: light.toggle
  - alias: Smart Switch 2 Double Press
    description: ''
    trigger:
    - event_data:
        event: 1004
        id: smart_switch_2
      event_type: deconz_event
      platform: event
    condition:
    - condition: state
      entity_id: light.balcony_ceiling
      state: 'on'
    action:
    - data_template:
        entity_id: input_number.balcony_ceiling_brightness_step
        value: >-
          {% set state = states.input_number.balcony_ceiling_brightness.state | int %}
          {% if state >= 100 %}
            {% set state = -10 %}
          {% elif state <= 10 %}
            {% set state = 10 %}
          {% else %}
            {% set state = states.input_number.balcony_ceiling_brightness_step.state | int %}
          {% endif %}
          {{ state | int }}
      entity_id: input_number.balcony_ceiling_brightness_step
      service: input_number.set_value
    - data_template:
        entity_id: input_number.balcony_ceiling_brightness
        value: >-
          {% set state = states.input_number.balcony_ceiling_brightness.state | int %}
          {% if state >= 100 %}
            {% set state = 90 %}
          {% elif state <= 10 %}
            {% set state = 20 %}
          {% else %}
            {% set step = states.input_number.balcony_ceiling_brightness_step.state | int %}
            {% set state = state + step %}
          {% endif %}
          {{ state | int }}
      entity_id: input_number.balcony_ceiling_brightness
      service: input_number.set_value
    - data_template:
        entity_id: light.balcony_ceiling
        brightness_pct: '{{ states.input_number.balcony_ceiling_brightness.state | int }}'
      entity_id: light.balcony_ceiling
      service: light.turn_on
  - alias: Smart Switch 2 Long Press
    description: ''
    trigger:
    - event_data:
        event: 1003
        id: smart_switch_2
      event_type: deconz_event
      platform: event
    condition:
    - condition: state
      entity_id: light.balcony_ceiling
      state: 'on'
    action:
    - data_template:
        entity_id: input_number.balcony_ceiling_mired_step
        value: >-
          {% set state = states.input_number.balcony_ceiling_mired.state | float %}
          {% if state >= 500 %}
            {% set state = -34.7 %}
          {% elif state <= 153 %}
            {% set state = 34.7 %}
          {% else %}
            {% set state = states.input_number.balcony_ceiling_mired_step.state | float %}
          {% endif %}
          {{ state | float }}
      entity_id: input_number.balcony_ceiling_mired_step
      service: input_number.set_value
    - data_template:
        entity_id: input_number.balcony_ceiling_mired
        value: >-
          {% set state = states.input_number.balcony_ceiling_mired.state | float %}
          {% set step = states.input_number.balcony_ceiling_mired_step.state | float %}
          {% if (state + step) >= 500 %}
            {% set state = 500 %}
          {% elif (state + step) <= 153 %}
            {% set state = 153 %}
          {% else %}
            {% set state = state + step %}
          {% endif %}
          {{ state | int }}
      entity_id: input_number.balcony_ceiling_mired
      service: input_number.set_value
    - data_template:
        entity_id: light.balcony_ceiling
        color_temp: '{{ states.input_number.balcony_ceiling_mired.state | int }}'
      entity_id: light.balcony_ceiling
      service: light.turn_on
  - alias: Smart Switch 2 Shake
    description: ''
    trigger:
    - event_data:
        event: 1007
        id: smart_switch_2
      event_type: deconz_event
      platform: event
    condition:
    - condition: state
      entity_id: light.balcony_ceiling
      state: 'on'
    action:
    - data_template:
        entity_id: input_number.balcony_ceiling_mired
        value: >-
          {% set state = states.input_number.balcony_ceiling_mired.state | float %}
          {% if state != 500 %}
            {% set state = 500 %}
          {% else %}
            {% set state = 153 %}
          {% endif %}
          {{ state | int }}
      entity_id: input_number.balcony_ceiling_mired
      service: input_number.set_value
    - data_template:
        entity_id: light.balcony_ceiling
        color_temp: '{{ states.input_number.balcony_ceiling_mired.state | int }}'
      entity_id: light.balcony_ceiling
      service: light.turn_on
  - alias: Smart Switch 3 Single Press
    description: ''
    trigger:
    - event_data:
        event: 1002
        id: smart_switch_3
      event_type: deconz_event
      platform: event
    condition: []
    action:
    - entity_id: switch.light_bedroom_ceiling
      service: switch.toggle
  - alias: Smart Switch 3 Double Press
    description: ''
    trigger:
    - event_data:
        event: 1004
        id: smart_switch_3
      event_type: deconz_event
      platform: event
    condition: []
    action:
    - entity_id: switch.light_bedroom_wall
      service: switch.toggle
